---
- name: install nginx
  apt: name=nginx state=present

- name: copy new virtual host
  template:
    src=nginx-virtual-host.j2
    dest=/etc/nginx/sites-available/vagrant

- name: remove default virtual host
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - restart nginx

- name: enable new virtual host
  file:
    src=/etc/nginx/sites-available/vagrant
    dest=/etc/nginx/sites-enabled/vagrant
    state=link
  notify:
    - restart nginx
