---
- name: Ensure Nginx is installed.
  apt: name=nginx state=present

- name: Copy new virtual hosts file.
  template:
    src=nginx-virtual-host.j2
    dest=/etc/nginx/sites-available/vagrant

- name: Disable default virtual hosts file.
  file:
    path=/etc/nginx/sites-enabled/default
    state=absent
  notify:
    - restart nginx

- name: Enable new virtual hosts file.
  file:
    src=/etc/nginx/sites-available/vagrant
    dest=/etc/nginx/sites-enabled/vagrant
    state=link
  notify:
    - restart nginx
